import "dotenv/config";

export const ENV = {
  PORT: process.env.PORT || 5151,
  MONGO_URI: process.env.MONGO_URI,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  NODE_ENV: process.env.NODE_ENV,
  CLODINARY_CLOUD_NAME: process.env.CLODINARY_CLOUD_NAME,
  CLODINARY_API_KEY: process.env.CLODINARY_API_KEY,
  CLODINARY_API_SECRET: process.env.CLODINARY_API_SECRET,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  CLIENT_URL: process.env.CLIENT_URL,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
};
